FROM nginx:1.9.0

ADD nginx.conf /etc/nginx/conf.d/default.conf 
ADD index.html /var/www/imageserver/reader/reader.html
ADD js /var/www/imageserver/reader/js
ADD favicon.ico /var/www/imageserver/favicon.ico
ADD robots.txt /var/www/imageserver/robots.txt
