nginx:
  build: ./nginx
  volumes:
    - /home/secikd/data:/var/www/imageserver
  links:
    - imageserver:imageserver
  ports:
    - "80:80"
  restart:
    always

memcached:
  image: memcached:1.4.24
  restart:
    always

imageserver:
  build: ./imageserver
  volumes:
    - /home/secikd/data:/data
  links:
    - memcached:memcached
  restart:
    always
