kramerius:
  image: moravianlibrary/kramerius
  volumes:
    - /data/kramerius/foxml-import:/data/foxml-import
  ports:
    - "8080:8080"
  environment:
    - TOMCAT_PASSWORD=tomcat
  links:
    - krameriusPostgres:krameriusPostgres
    - imageserver:imageserver
    - riTriplesPostgres:riTriplesPostgres
    - fcrepo:fcrepo
    - solr:solr
krameriusPostgres:
  image: "martinrumanek/postgres:9.3"
  environment:
    - POSTGRES_USER=fedoraAdmin
    - POSTGRES_PASSWORD=fedoraAdmin
    - POSTGRES_DB=kramerius
  volumes:
    - /data/kramerius/postgres:/var/lib/postgresql/data
imageserver:
  image: moravianlibrary/iipsrv-nginx
  links:
    - iipsrv:imageserver
  volumes:
    - /data/logs:/logs
    - /etc/localtime:/etc/localtime
memcached:
  image: memcached
  command: memcached -u root -m 1024
iipsrv:
  image: moravianlibrary/iipsrv-imageserver
  links:
    - memcached:memcached
  volumes:
    - /data/imageserver:/data
  environment:
    - CHILDREN=6
    - PORT=9000
    - LOGFILE=/logs/iipsrv.log
    - FILESYSTEM_PREFIX=/data/
    - VERBOSITY=100
    - JPEG_QUALITY=90
    - MAX_IMAGE_CACHE_SIZE=10
    - MAX_CVT=30000
    - MAX_LAYERS=10
    - MEMCACHED_SERVERS=memcached
fcrepo:
  image: moravianlibrary/fcrepo:3.6.2
  volumes:
    - /data/fcrepo/datastreams:/usr/local/fedora/data/datastreams
    - /data/fcrepo/objects:/usr/local/fedora/data/objects
    - /data/fcrepo/resourceIndex:/usr/local/fedora/data/resourceIndex
  ports:
    - "8080"
  links:
    - fedoraPostgres:fedoraPostgres
    - riTriplesPostgres:riTriplesPostgres
fedoraPostgres:
  image: "martinrumanek/postgres:9.3"
  environment:
    - POSTGRES_USER=fedoraAdmin
    - POSTGRES_PASSWORD=fedoraAdmin
    - POSTGRES_DB=fedora3
  volumes:
    - /data/fcrepo/fedorapostgres:/var/lib/postgresql/data
riTriplesPostgres:
  image: "martinrumanek/postgres:9.3"
  environment:
    - POSTGRES_USER=fedoraAdmin
    - POSTGRES_PASSWORD=fedoraAdmin
    - POSTGRES_DB=riTriples
  volumes:
    - /data/fcrepo/ritriplespostgres:/var/lib/postgresql/data
solr:
  image: moravianlibrary/solr
  ports:
    - "8080"

