kramerius:
  image: moravianlibrary/kramerius
  volumes:
    - /data/kramerius/foxml-import:/data/foxml-import
    - /data/kramerius/.kramerius4:/root/.kramerius4
  ports:
    - "80:8080"
  links:
    - krameriusPostgres:krameriusPostgres
    - riTriplesPostgres:riTriplesPostgres
    - fcrepo:fcrepo
    - solr:solr
krameriusPostgres:
  image: "postgres:9.3"
  environment:
    - POSTGRES_USER=fedoraAdmin
    - POSTGRES_PASSWORD=fedoraAdmin
    - POSTGRES_DB=kramerius
  volumes:
    - /data/kramerius/postgres:/var/lib/postgresql/data
fcrepo:
  image: moravianlibrary/fcrepo:3.6.2
  volumes:
    - /data/fcrepo/datastreams:/usr/local/fedora/data/datastreams
    - /data/fcrepo/objects:/usr/local/fedora/data/objects
    - /data/fcrepo/resourceIndex:/usr/local/fedora/data/resourceIndex
  ports:
    - "8080:8080"
  links:
    - fedoraPostgres:fedoraPostgres
    - riTriplesPostgres:riTriplesPostgres
fedoraPostgres:
  image: "postgres:9.3"
  environment:
    - POSTGRES_USER=fedoraAdmin
    - POSTGRES_PASSWORD=fedoraAdmin
    - POSTGRES_DB=fedora3
  volumes:
    - /data/fcrepo/fedorapostgres:/var/lib/postgresql/data
riTriplesPostgres:
  image: "postgres:9.3"
  environment:
    - POSTGRES_USER=fedoraAdmin
    - POSTGRES_PASSWORD=fedoraAdmin
    - POSTGRES_DB=riTriples
  volumes:
    - /data/fcrepo/ritriplespostgres:/var/lib/postgresql/data
solr:
  image: moravianlibrary/solr
  ports:
    - "8080"
  volumes:
    - /data/solr:/usr/local/solr/data
