kramerius:
  build: .
  volumes:
    - /data/kramerius/foxml-import:/data/foxml-import
  ports:
    - "8080"
  links:
    - krameriusPostgres:krameriusPostgres
    - imageserver:imageserver
  external_links:
    - 362_riTriplesPostgres_1:riTriplesPostgres
    - 362_fcrepo_1:fcrepo
    - solr_solr_1:solr
krameriusPostgres:
  image: "martinrumanek/postgres:9.3"
  environment:
    - POSTGRES_USER=fedoraAdmin
    - POSTGRES_PASSWORD=fedoraAdmin
    - POSTGRES_DB=kramerius
  volumes:
    - /data/kramerius/postgres:/var/lib/postgresql/data
imageserver:
  image: moravianlibrary/iipsrv-nginx
  links:
    - iipsrv:imageserver
  volumes:
    - /data/logs:/logs
    - /etc/localtime:/etc/localtime
memcached:
  image: moravianlibrary/iipsrv-memcached
  command: memcached -u root -m 1024
iipsrv:
  image: moravianlibrary/iipsrv-imageserver
  links:
    - memcached:memcached
  volumes:
    - /data/imageserver:/data
  environment:
    - CHILDREN=6
    - PORT=9000
    - LOGFILE=/logs/iipsrv.log
    - FILESYSTEM_PREFIX=/data/
    - VERBOSITY=100
    - JPEG_QUALITY=90
    - MAX_IMAGE_CACHE_SIZE=10
    - MAX_CVT=30000
    - MAX_LAYERS=10
    - MEMCACHED_SERVERS=memcached

