krameriusPostgres:
  image: "postgres:9.3"
  environment:
    - POSTGRES_USER=fedoraAdmin
    - POSTGRES_PASSWORD=fedoraAdmin
    - POSTGRES_DB=kramerius
  ports:
    - "5432:5432"
  volumes:
    - /data/kramerius/postgres:/var/lib/postgresql/data
fcrepo:
  image: moravianlibrary/fcrepo:3.6.2
  volumes:
    - /data/fcrepo/datastreams:/usr/local/fedora/data/datastreams
    - /data/fcrepo/objects:/usr/local/fedora/data/objects
    - /data/fcrepo/resourceIndex:/usr/local/fedora/data/resourceIndex
  environment:
    - FEDORA_PASSWORD=fedoraAdmin
  ports:
    - "8081:8080"
  links:
    - fedoraPostgres:fedoraPostgres
    - riTriplesPostgres:riTriplesPostgres
fedoraPostgres:
  image: "postgres:9.3"
  environment:
    - POSTGRES_USER=fedoraAdmin
    - POSTGRES_PASSWORD=fedoraAdmin
    - POSTGRES_DB=fedora3
  volumes:
    - /data/fcrepo/fedorapostgres:/var/lib/postgresql/data
  ports:
    - "5433:5432"
riTriplesPostgres:
  image: "postgres:9.3"
  environment:
    - POSTGRES_USER=fedoraAdmin
    - POSTGRES_PASSWORD=fedoraAdmin
    - POSTGRES_DB=riTriples
  ports:
    - "5434:5432"
  volumes:
    - /data/fcrepo/ritriplespostgres:/var/lib/postgresql/data
solr:
  image: moravianlibrary/solr
  ports:
    - "8082:8080"
  volumes:
    - /data/solr:/usr/local/solr/data
