FROM ubuntu:latest
RUN apt-get update && apt-get install -y python-pip nano && pip install elasticsearch-curator &&  rm -rf /var/lib/apt/lists/*


ADD crontab /etc/cron.d/hello-cron
RUN chmod 0644 /etc/cron.d/hello-cron
RUN touch /var/log/cron.log

CMD cron && tail -f /var/log/cron.log 
