nginx:
  image: moravianlibrary/iipsrv-nginx
  volumes:
    - /data/imageserver:/var/www/imageserver
  links:
    - imageserver:imageserver
  ports:
    - "80:80"
  restart:
    always
memcached:
  image: memcached:1.4.24
  restart:
    always
imageserver:
  image: moravianlibrary/iipsrv-imageserver
  volumes:
    - /data/imageserver:/data
  links:
    - memcached:memcached
  restart:
    always
