nginx:
  build: ./nginx
  volumes:
    - /data/imageserver:/var/www/imageserver/data
  links:
    - imageserver:imageserver
  environment:
    - "TZ=Europe/Prague"
  ports:
    - "80:80"
  log_driver: "json-file"
  log_opt:
    max-size: "100m"
    max-file: "1"
  restart:
    always

memcached:
  image: memcached:latest
  environment:
    - "TZ=Europe/Prague"
  log_driver: "json-file"
  log_opt:
    max-size: "100m"
    max-file: "1"
  restart:
    always

imageserver:
  build: ./imageserver
  volumes:
    - /data/imageserver:/data
  environment:
    - "TZ=Europe/Prague"
  links:
    - memcached:memcached
  log_driver: "json-file"
  log_opt:
    max-size: "100m"
    max-file: "1"
  restart:
    always
