nginx:
  build: ./nginx
  volumes:
    - /home/secikd/data:/var/www/imageserver/data
    - /etc/localtime:/etc/localtime
  links:
    - imageserver:imageserver
  ports:
    - "80:80"
  restart:
    always

memcached:
  image: memcached:1.4.24
  volumes:
    - /etc/localtime:/etc/localtime
  restart:
    always

imageserver:
  build: ./imageserver
  volumes:
    - /home/secikd/data:/data
    - /etc/localtime:/etc/localtime
  links:
    - memcached:memcached

